# Generated by Django 4.0.5 on 2022-06-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assignee_user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author_user_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author_user_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
